# import tensorflow

In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.16.2


## Load data sets

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0 # 255 is maximum range of pixel point

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


## Builds machine learning model

In [7]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [17]:
pretictions = model(x_train[:1]).numpy()
pretictions

array([[0.19036092, 0.07080684, 0.0637549 , 0.06527378, 0.10073174,
        0.13644688, 0.06517801, 0.07947884, 0.05976583, 0.16820225]],
      dtype=float32)

In [18]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [19]:
loss_fn(y_train[:1], pretictions).numpy()

2.2671912

In [20]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

## Training and Evalution to model

In [21]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


c:\Program Files\Python312\Lib\site-packages\keras\src\backend\tensorflow\nn.py:609: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8577 - loss: 0.4814
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9566 - loss: 0.1453
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9660 - loss: 0.1108
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9711 - loss: 0.0919
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9764 - loss: 0.0739


In [22]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test, y_test, verbose=2)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9793 - loss: 0.0652
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9808 - loss: 0.0599
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9828 - loss: 0.0522
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9849 - loss: 0.0468
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9851 - loss: 0.0427


c:\Program Files\Python312\Lib\site-packages\keras\src\backend\tensorflow\nn.py:609: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


313/313 - 1s - 2ms/step - accuracy: 0.9801 - loss: 0.0706


[0.07057508826255798, 0.9800999760627747]

In [23]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [24]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533713, 0.08533713, 0.08533713, 0.08533975, 0.08533713,
        0.08533714, 0.08533713, 0.23196319, 0.08533714, 0.08533713],
       [0.08533674, 0.08533674, 0.23196921, 0.08533677, 0.08533674,
        0.08533674, 0.08533674, 0.08533674, 0.08533674, 0.08533674],
       [0.08534482, 0.23184165, 0.08536829, 0.08534531, 0.08534495,
        0.08534483, 0.08534569, 0.08537421, 0.08534547, 0.08534483],
       [0.23196647, 0.08533692, 0.08533704, 0.08533692, 0.08533692,
        0.08533717, 0.08533742, 0.08533692, 0.08533692, 0.08533727],
       [0.08534157, 0.08534157, 0.08534157, 0.08534157, 0.23189293,
        0.08534157, 0.08534157, 0.08534167, 0.08534157, 0.08537438]],
      dtype=float32)>